name: Build and Deploy

on:
  push:
    branches:
      -main

jobs:
  build-deploy:
    name: Deploy chat app
    runs-on: ubuntu-latest

  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17

    - name: Test
      run: mvn -B test --file pom.xml
